"""empty message

Revision ID: 0593738ffc73
Revises: 
Create Date: 2021-03-17 01:11:32.489289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0593738ffc73'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('num_bedrooms', sa.String(), nullable=True),
    sa.Column('num_bathrooms', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('prop_type', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property_profile')
    # ### end Alembic commands ###
